cat_url = ['https://media.tenor.com/F2hvezp1-SoAAAAM/soggy-cat-soggy-cat-jumpscare.gif', 
           'https://media.tenor.com/M8CrcswsP04AAAAM/silly-silly-cat.gif', 
           'https://media.tenor.com/ZjO9pAw35wIAAAAM/post-this.gif', 
           'https://media.tenor.com/D6ewisp89HIAAAAM/this-cat-i-have-hired-this-cat-to-stare-at-you.gif',
           'https://media.tenor.com/u2uD9WCRTi0AAAAM/on-my-way-cat-run.gif',
           'https://media.tenor.com/mWKaoVamqwcAAAAM/cat-staring-cat.gif',
           'https://media.tenor.com/7yqmvYgQBZAAAAAM/server-cat.gif',
           'https://media.tenor.com/SeoYom_1lYQAAAAM/good-morning-cat-bump.gif',
           'https://media.tenor.com/7-0mRNtPj8kAAAAM/cat-kitty.gif',
           'https://media.tenor.com/uPYKEx9pzMsAAAAM/drinked.gif']

dog_url = ['https://media.tenor.com/8TXyrUU4QLQAAAAM/knock-knock-dog-of-wisdom-2.gif',
           'https://media.tenor.com/UzqbrxMXMIAAAAAM/sniff-sniff-sniffing.gif',
           'https://media.tenor.com/Nl8ktVNpPGgAAAAM/dog.gif',
           'https://media.tenor.com/g6L8QBAralwAAAAM/skaya-skaya-siberian.gif',
           'https://media.tenor.com/Tjkaft9VkigAAAAM/shibe-hold.gif',
           'https://media.tenor.com/2oefZ-xkoTYAAAAM/husky-cute.gif',
           'https://media.tenor.com/aG59nHPQ5ZUAAAAM/dog-looking.gif',
           'https://media.tenor.com/LuAsjWs57AAAAAAM/funny-dog-cute-dog.gif',
           'https://media.tenor.com/JxPnrRIzIGQAAAAM/shiba-inu-dog.gif',
           'https://media.tenor.com/J2rAw1lDFC0AAAAM/lua-husky.gif']

otter_url = ['https://media.tenor.com/Gn3Bd_ODSdoAAAAM/hug-kiss.gif',
             'https://media.tenor.com/XXpl59NmzLYAAAAM/otter-bored.gif',
             'https://media.tenor.com/9Ty_Y11ixUYAAAAM/otter-otter-aty.gif',
             'https://media.tenor.com/WCn5MmZPT0wAAAAM/otter-stim.gif',
             'https://media.tenor.com/1-r6cKxBhV0AAAAM/otter-jumpscare.gif',
             'https://media.tenor.com/xrZJO5R_ArUAAAAM/shigu-otter.gif',
             'https://media.tenor.com/Dkl0K4lVk40AAAAM/otter-water.gif',
             'https://media.tenor.com/ig6aYuKn8XgAAAAM/otter-otter-aty.gif',
             'https://media.tenor.com/bn6erNcmKDMAAAAM/otter-holding-hands.gif',
             'https://media.tenor.com/smrO8_V726wAAAAM/otter-attack-otter-bite.gif']

capybara_url = ['https://media.tenor.com/JfJNZpzKcDwAAAAM/home-time.gif',
                'https://media.tenor.com/kGI-yD_1ag0AAAAM/capybara-eating.gif',
                'https://media.tenor.com/Ldk2j3SqRU4AAAAM/capy-capybara.gif',
                'https://media.tenor.com/UxJXDH8MMpQAAAAM/home-time.gif',
                'https://media.tenor.com/poCBQ7TGhZsAAAAM/capybarochka.gif',
                'https://media.tenor.com/OK56ZlhzYOMAAAAM/cry-about-it-capybara.gif',
                'https://media.tenor.com/V6Gj0IDvU7oAAAAM/he-hops-out-at-the-after-party-meme.gif',
                'https://media.tenor.com/VFeMxQ6UELkAAAAM/get-real-capybara.gif',
                'https://media.tenor.com/IfMyy-WYACkAAAAM/capybara.gif',
                'https://media.tenor.com/ZxBi_52Ls-QAAAAM/sploshj-capybara.gif']